#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the factorial function below.
fac_cache = {}
def factorial(n):
    if n in fac_cache:
        return fac_cache[n]
    
    if n == 1:
       value = n
  #  elif n < 1:
  #     return ("NA")
    else:
       value = n*factorial(n-1)

    fac_cache[n] = value
    return value


if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input())

    result = factorial(n)

    fptr.write(str(result) + '\n')

    fptr.close()
