#!/bin/python3

import math
import os
import random
import re
import sys


def check_n(n):
    if n%2 != 0:
        print('Weird')
    elif (n%2 == 0) and 2<=n<=5:
        print('Not Weird')
    elif (n%2 == 0) and 6 <= n <= 20:
        print('Weird')
    elif n > 20:
        print('Not Weird')



if __name__ == '__main__':
    N = int(input())
    check_n(N)
